services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always
    env_file:
      - ./client/.env
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
